SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SteamGame](
	[GameId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](250) NOT NULL,
	[ReleaseDate] [datetime] NULL,
	[LastUpdate] [datetime] NULL,
	[Flags] [int] NULL,
	[AppId] [int] NULL,
 CONSTRAINT [PK_SteamGames] PRIMARY KEY CLUSTERED 
(
	[GameId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[SteamGamePrice](
	[PriceId] [int] IDENTITY(1,1) NOT NULL,
	[Price] [decimal](5, 2) NULL,
	[RegionCode] [varchar](50) NULL,
	[GameId] [int] NULL,
 CONSTRAINT [PK_SteamGamePrices] PRIMARY KEY CLUSTERED 
(
	[PriceId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SteamGamePrice]  WITH CHECK ADD  CONSTRAINT [FK_SteamGamePrices_SteamGames] FOREIGN KEY([GameId])
REFERENCES [dbo].[SteamGame] ([GameId])
GO

ALTER TABLE [dbo].[SteamGamePrice] CHECK CONSTRAINT [FK_SteamGamePrices_SteamGames]
GO